name: Jason Burton
favicon: null
layout_spectrum: 1
typography_spectrum: 0.13401
title: Jason Burton
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#47273e'
    - '#ab313e'
    - '#f98800'
    - '#e14920'
    - '#ffc812'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
