name: Jason Burton Family
favicon: null
layout_spectrum: 1
typography_spectrum: 0.08523
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040203'
    - '#73355a'
    - '#f2544a'
    - '#f6bb00'
    - '#550202'
  brandStrength: 0.125
  lightness: 0.75
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
