name: Jason and Amy Burton
favicon: null
layout_spectrum: 0.66169
typography_spectrum: 0.09607
title: Jason and Amy Burton
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#47273e'
    - '#ab313e'
    - '#f98800'
    - '#e14920'
    - '#ffc812'
  brandStrength: 0
  lightness: 0
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
